# -*- mode: ruby -*-
# vi: set ft=ruby :
#require_relative 'network_interfaces'
Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"

  machines = {
    'node1'    => { :ip => '10.1.0.10'},
    #'node2'    => { :ip =>'10.1.0.12'},
  }

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = #false
  config.hostmanager.include_offline = true

  config.ssh.pty = true

  machines.each do | hostname, attrs|
    config.vm.define hostname do |machine|
      machine.vm.hostname = hostname
      machine.vm.network :private_network, :ip => attrs[:ip],  id: :local
      #machine.vm.network :forwarded_port, host: 8888, guest: 80
      machine.vm.provider "virtualbox" do | v |
        v.memory = "8096"
        v.cpus = "4"
      end

    end
  end
end
