apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
  name: hello-world
spec:
  ports:
    -
      name: http
      port: 80
      targetPort: http
  selector:
    app: hello-world
  type: LoadBalancer

