apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: elasticsearch
  name: elasticsearch
spec:
  selector:
    name: elk
  type: NodePort
  ports:
  - name: port1
    port: 9200
    targetPort: 9200
  - name: port2
    port: 9300
    targetPort: 9300
  selector:
    service: elasticsearch
status:
  loadBalancer: {}
