apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    app: mysql-app
spec:
  replicas: 1
  selector:
    app: mysql-app
  template:
    metadata:
      name: mysql
      labels:
        app: mysql-app
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306