apiVersion: v1
kind: ReplicationController
metadata:
  name: "hello-world"
spec:
  replicas: 4
  selector:
    app: "hello-world"
  template:
    metadata:
      labels:
        app: "hello-world"
    spec:
      containers:
        -
          image: tutum/hello-world
          name: "hello-world"
          ports:
            -
              containerPort: 8080
              name: http
