postgres:
  restart: always
  image: postgres:9.3
  ports:
    - '5432:5432'
  environment:
    - POSTGRES_PASSWORD=secret
    - POSTGRES_USER=sentry
  volumes:
    - /var/lib/postgresql/:/var/lib/postgresql
  container_name: sentry-postgres
redis:
  image: redis
  ports:
    - "6379:6379"
  restart: always
  container_name: sentry-redis
sentry:
  image: sentry
  environment:
    - SENTRY_SERVER_EMAIL=
    - SENTRY_EMAIL_HOST=
    - SENTRY_EMAIL_PORT=
    - SENTRY_EMAIL_USER=
    - SENTRY_EMAIL_PASSWORD=
    - SENTRY_EMAIL_USE_TLS=True
    - SENTRY_SECRET_KEY=
  volumes:
    - /etc/sentry:/etc/sentry
  ports:
    - "127.0.0.1:8080:9000"
  links:
    - postgres
    - redis
  restart: always
  container_name: my-sentry
beat:
  image: sentry
  environment:
    - SENTRY_SERVER_EMAIL=
    - SENTRY_EMAIL_HOST=
    - SENTRY_EMAIL_PORT=
    - SENTRY_EMAIL_USER=
    - SENTRY_EMAIL_PASSWORD=
    - SENTRY_EMAIL_USE_TLS=True
    - SENTRY_SECRET_KEY=
  links:
    - postgres
    - redis
  restart: always
  command: sentry celery beat
  container_name: sentry-celery-beat
worker:
  image: sentry
  environment:
    - SENTRY_SERVER_EMAIL=
    - SENTRY_EMAIL_HOST=
    - SENTRY_EMAIL_PORT=
    - SENTRY_EMAIL_USER=
    - SENTRY_EMAIL_PASSWORD=
    - SENTRY_EMAIL_USE_TLS=True
    - SENTRY_SECRET_KEY=
  links:
    - postgres
    - redis
  restart: always
  command: sentry celery worker
  container_name: sentry-celery-worker
