apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-scripts
  # namespace: gitlab
data:
  entrypoint: |
    #!/bin/bash

    set -xe

    cp /scripts/config.toml /etc/gitlab-runner/

    # Register the runner
    /entrypoint register --non-interactive \
      --url http://gitlab.gitlab:8005/ci \
      --executor kubernetes \
      --kubernetes-privileged=true

    # Start the runner
    /entrypoint run --user=gitlab-runner \
      --working-directory=/home/gitlab-runner
  config.toml: |
    concurrent = 10
    check_interval = 1
