apiVersion: "v1"
kind: "Pod"
metadata:
  name: "mysql"
  labels:
    type: "database"
  namespace: mailship
spec:
  containers:
    - name: mysql
      image: "docker-registry.vccloud.vn/lamdt/mysql-server:5.7.12"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypass
      ports:
        - containerPort: 3306
          name: "mysql"
      volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: "mysql"
  volumes:
    - name: mysql
      persistentVolumeClaim:
        claimName: "mysql"
  imagePullSecrets:
    - name: "key"