apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: kibana
  name: kibana
spec:
  selector:
    name: kibana
  type: NodePort
  ports:
  - name: "5601"
    port: 5601
    targetPort: 5601
  selector:
    service: kibana
status:
  loadBalancer: {}
