apiVersion: v1
kind: Service
metadata:
  name: gitlab
  # namespace: gitlab
  labels:
    name: gitlab
spec:
  selector:
    name: gitlab
  type: NodePort
  ports:
    - name: git
      port: 8000
      targetPort: 8080
    - name: ssh
      port: 22
      targetPort: ssh
    - name: mattermost
      port: 8065
      targetPort: mattermost
    - name: registry
      port: 8105
      targetPort: registry
    - name: workhorse
      port: 8005
      targetPort: workhorse
    - name: prometheus
      port: 9090
      targetPort: prometheus
    - name: node-exporter
      port: 9100
      targetPort: node-exporter
