apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: gitlab-postgresql
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /srv/gitlab-postgresql