--- 
apiVersion: v1
kind: Pod
metadata: 
  name: www
spec: 
  containers: 
    - 
      image: nginx
      name: nginx
      ports: 
        - 
          containerPort: 80
      volumeMounts: 
        - 
          mountPath: /srv/www
          name: www-data
          readOnly: true
    - 
      env: 
        - 
          name: GIT_REPO
          value: "http://github.com/some/repo.git"
      image: kubernetes/git-monitor
      name: git-monitor
      volumeMounts: 
        - 
          mountPath: /data
          name: www-data
  volumes: 
    - 
      emptyDir: {}
      name: www-data
