apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres
  labels:
    app: postgres-app
spec:
  replicas: 1
  selector:
    app: postgres-app
  template:
    metadata:
      name: postgres
      labels:
        app: postgres-app
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432